import React,{useCallback,useState} from 'react';
import {adminApi} from '../../services/api/admin';
import {useAdminRead,ReadState} from './shared';
import {AdminUserProjectFilter} from './AdminUserProjectFilter';
import {useAuth} from '../auth/AuthProvider';

export function AdminUsers({api=adminApi}) {
 const {user}=useAuth();const [filters,setFilters]=useState({keyword:'',role:'',enabled:'',projectId:'',page:0});const [creating,setCreating]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(signal=>api.users({...filters,size:20},{signal}),[api,filters]);const state=useAdminRead(JSON.stringify(filters),load);
 const filter=(key,value)=>setFilters({...filters,[key]:value,page:0});
 async function update(u,change){if(busy)return;setBusy(true);setError('');try{await api.updateUser(u.id,{...change,expectedVersion:u.version});state.retry();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><div className="admin-page-heading"><h1>Người dùng</h1><button onClick={()=>setCreating(true)}>Tạo tài khoản</button></div>{creating&&<UserForm api={api} onCancel={()=>setCreating(false)} onSaved={()=>{setCreating(false);state.retry();}}/>}
 <section className="admin-card admin-filters"><label>Tìm username hoặc tên<input type="search" maxLength={100} value={filters.keyword} onChange={e=>filter('keyword',e.target.value)}/></label><label>Vai trò<select value={filters.role} onChange={e=>filter('role',e.target.value)}><option value="">Tất cả</option>{['ADMIN','PM','TESTER','DEV'].map(r=><option key={r}>{r}</option>)}</select></label><label>Trạng thái<select value={filters.enabled} onChange={e=>filter('enabled',e.target.value)}><option value="">Tất cả</option><option value="true">Hoạt động</option><option value="false">Đã khóa</option></select></label><AdminUserProjectFilter api={api} value={filters.projectId} onChange={id=>filter('projectId',id)}/></section>
 {error&&<p role="alert">{error} <button onClick={state.retry}>Tải dữ liệu hiện hành</button></p>}<ReadState {...state}/>{state.data&&<section className="admin-card"><p>{state.data.totalElements} tài khoản · Trang {filters.page+1}</p><div className="admin-table-scroll" tabIndex={0}><table><thead><tr><th>Tài khoản</th><th>Vai trò</th><th>Trạng thái</th><th>Dự án</th><th>Tạo lúc</th><th>Thao tác</th></tr></thead><tbody>{state.data.items.map(u=><tr key={u.id}><th>{u.displayName}<small> @{u.username}</small></th><td>{u.role}</td><td>{u.enabled?'Hoạt động':'Đã khóa'}</td><td>{u.memberships?.length?u.memberships.map(m=><p key={m.projectId}><a href={`#/admin/projects/${m.projectId}`}>{m.code}</a> · {m.projectRole}</p>):'Chưa có dự án'}</td><td><time dateTime={u.createdAt} title={u.createdAt}>{new Date(u.createdAt).toLocaleString('vi-VN')}</time></td><td><div className="admin-actions"><button disabled={busy||u.id===user.id} onClick={()=>update(u,{enabled:!u.enabled})}>{u.enabled?'Khóa':'Mở khóa'}</button>{u.role==='PM'&&<button disabled={busy} onClick={()=>update(u,{canCreateUsers:!u.canCreateUsers})}>{u.canCreateUsers?'Thu hồi quyền tạo Tester':'Cấp quyền tạo Tester'}</button>}</div></td></tr>)}</tbody></table></div>{!state.data.items.length&&<p>Không có tài khoản phù hợp.</p>}<div className="admin-pagination"><button disabled={!filters.page} onClick={()=>setFilters({...filters,page:filters.page-1})}>Trang trước</button><button disabled={(filters.page+1)*20>=state.data.totalElements} onClick={()=>setFilters({...filters,page:filters.page+1})}>Trang sau</button></div></section>}</>;
}
function UserForm({api,onSaved,onCancel}) {
 const [draft,setDraft]=useState({username:'',displayName:'',password:'',role:'TESTER'});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api.createUser(draft);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <form className="admin-card admin-form" onSubmit={save}><h2>Tạo tài khoản</h2>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy}><label>Tên đăng nhập<input required pattern="[A-Za-z0-9][A-Za-z0-9._-]{2,63}" value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label>Tên hiển thị<input required maxLength={100} value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Mật khẩu<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><label>Vai trò tài khoản<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}>{['TESTER','DEV','PM','ADMIN'].map(r=><option key={r}>{r}</option>)}</select></label><div className="admin-actions"><button type="submit">{busy?'Đang tạo…':'Lưu tài khoản'}</button><button type="button" onClick={onCancel}>Hủy</button></div></fieldset></form>;
}
