import React,{useCallback,useState} from 'react';
import {adminApi} from '../../services/api/admin';
import {AdminUserProjectFilter} from './AdminUserProjectFilter';
import {useAdminRead,ReadState} from './shared';
import {assetStatuses} from './DeviceAssetForm';
export function DeviceAllocationDialog({asset,allocation,onSaved,onCancel,api=adminApi}) {
 const [projectId,setProjectId]=useState('');const [recipientUserId,setRecipient]=useState('');const [date,setDate]=useState('');const [note,setNote]=useState('');const [condition,setCondition]=useState('AVAILABLE');
 const [version,setVersion]=useState(allocation?.version??asset.version);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(signal=>projectId?api.members(projectId,{signal}):Promise.resolve([]),[api,projectId]);const people=useAdminRead(`recipients:${projectId}`,load);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{onSaved(await(allocation?api.returnDevice(allocation.id,{expectedVersion:version,conditionCode:condition,returnNote:note}):api.assignDevice({assetId:asset.id,projectId:Number(projectId),recipientUserId,expectedVersion:version,expectedReturnOn:date||null,handoverNote:note})));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function reload(){setBusy(true);try{if(allocation){const latest=await api.allocations({assetId:asset.id,history:true,size:100});const current=latest.items.find(a=>a.id===allocation.id);if(!current||current.returnedAt){setError('Lượt bàn giao đã được thu hồi. Đóng form và tải lại danh sách.');return;}setVersion(current.version);}else{const latest=await api.asset(asset.id);setVersion(latest.version);if(latest.status!=='AVAILABLE'){setError('Máy không còn sẵn sàng. Đóng form và tải lại danh sách.');return;}}setError('Đã tải phiên bản hiện hành; bản nháp được giữ. Kiểm tra trước khi gửi lại.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <form className="admin-card admin-form" onSubmit={save}><h2>{allocation?'Thu hồi':'Bàn giao'} {asset.assetCode}</h2>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy}>
 {allocation?<><p>{allocation.projectName} · {allocation.recipientName}</p><label>Tình trạng khi nhận<select value={condition} onChange={e=>setCondition(e.target.value)}>{Object.entries(assetStatuses).filter(([k])=>k!=='ALLOCATED').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p>Thời điểm thu hồi và người ghi nhận được lưu khi gửi.</p></>:<><AdminUserProjectFilter api={api} label="Dự án nhận máy" value={projectId} onChange={id=>{setProjectId(id);setRecipient('');}}/><ReadState {...people}/><label>Người nhận<select required value={recipientUserId} onChange={e=>setRecipient(e.target.value)}><option value="">Chọn thành viên</option>{people.data?.filter(m=>m.active).map(m=><option key={m.userId} value={m.userId}>{m.displayName} · {m.username}</option>)}</select></label><label>Ngày dự kiến trả<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></>}
 <label>Ghi chú bàn giao / thu hồi<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><button type="submit" disabled={!allocation&&(!projectId||!recipientUserId)}>Xác nhận {allocation?'thu hồi':'bàn giao'}</button><button type="button" onClick={onCancel}>Hủy</button>{error&&<button type="button" onClick={reload}>Tải phiên bản hiện hành, giữ bản nháp</button>}</fieldset></form>;
}
