package vn.syp.tms.integration;

import com.fasterxml.jackson.databind.*;
import java.io.ByteArrayOutputStream;
import java.net.URI;
import java.net.http.*;
import java.nio.ByteBuffer;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.Flow;
import org.springframework.stereotype.Component;

/** No redirects, retries, raw response logs, URL credentials, or unbounded response buffering. */
@Component
public class RedmineClient {
    public record Remote(long id,RedminePayload payload) {}
    public static class Failure extends RuntimeException {
        private final int httpStatus;
        private final boolean uncertain,retryable;
        private final long retryAfterSeconds;
        public Failure(String code,int httpStatus,boolean uncertain,boolean retryable,long retryAfterSeconds) {
            super(code);this.httpStatus=httpStatus;this.uncertain=uncertain;this.retryable=retryable;this.retryAfterSeconds=retryAfterSeconds;
        }
        public int httpStatus(){return httpStatus;}
        public boolean uncertain(){return uncertain;}
        public boolean retryable(){return retryable;}
        public long retryAfterSeconds(){return retryAfterSeconds;}
    }
    private final RedmineConfiguration config;
    private final ObjectMapper json;
    private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(3)).followRedirects(HttpClient.Redirect.NEVER).build();
    public RedmineClient(RedmineConfiguration config,ObjectMapper json){this.config=config;this.json=json;}
    public Remote read(long id,RedmineConfiguration.Mapping m,String marker) {
        var issue=remote(request("GET","/issues/"+id+".json",null).path("issue"),m,marker);
        if(issue.id()!=id)throw new Failure("REMOTE_IDENTITY_MISMATCH",200,false,false,0);
        return issue;
    }
    public List<Remote> find(RedmineConfiguration.Mapping m,String marker) {
        // Marker is generated by TMS; validate again at the outbound boundary, never concatenate user URLs.
        UUID.fromString(marker);
        var result=request("GET","/issues.json?project_id="+m.externalProjectId()+"&status_id=*&cf_"+m.correlationFieldId()+"="+marker+"&limit=2",null);
        if(!result.path("issues").isArray() || !result.path("total_count").canConvertToInt())throw invalid(false);
        var found=new ArrayList<Remote>();
        for(var item:result.path("issues"))found.add(remote(item,m,marker));
        if(result.path("total_count").asInt()!=found.size() || found.size()>2)throw new Failure("REMOTE_DUPLICATE_MARKER",200,false,false,0);
        return found;
    }
    public long create(RedminePayload payload,RedmineConfiguration.Mapping m) {
        var node=request("POST","/issues.json",payload.wire(m.correlationFieldId())).path("issue");
        if(!node.path("id").canConvertToLong() || node.path("id").asLong()<1)throw invalid(true);
        return node.path("id").asLong();
    }
    public void update(long id,RedminePayload payload,RedmineConfiguration.Mapping m){request("PUT","/issues/"+id+".json",payload.wire(m.correlationFieldId()));}
    private Remote remote(JsonNode item,RedmineConfiguration.Mapping m,String marker) {
        String actual=null;int matches=0;
        for(var field:item.path("custom_fields"))if(field.path("id").asLong()==m.correlationFieldId()){actual=field.path("value").asText();matches++;}
        if(item.path("id").asLong()<1 || item.path("project").path("id").asLong()!=m.externalProjectId()
            || item.path("tracker").path("id").asLong()!=m.trackerId() || matches!=1 || !marker.equals(actual))
            throw new Failure("REMOTE_IDENTITY_MISMATCH",200,false,false,0);
        if(!item.path("subject").isTextual() || !item.path("description").isTextual() || !item.path("is_private").isBoolean()
            || item.path("status").path("id").asLong()<1 || item.path("priority").path("id").asLong()<1)throw invalid(false);
        return new Remote(item.path("id").asLong(),new RedminePayload(m.externalProjectId(),m.trackerId(),item.path("status").path("id").asLong(),item.path("priority").path("id").asLong(),
            item.path("subject").asText(),item.path("description").asText().replace("\r\n","\n"),marker,item.path("is_private").asBoolean()));
    }
    private JsonNode request(String method,String path,Object body) {
        boolean write=!method.equals("GET");CompletableFuture<HttpResponse<byte[]>> future=null;
        try {
            var request=HttpRequest.newBuilder(URI.create(config.base()+path)).timeout(Duration.ofSeconds(10))
                .header("X-Redmine-API-Key",config.apiKey()).header("Accept","application/json")
                .header("Content-Type","application/json").method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofByteArray(json.writeValueAsBytes(body))).build();
            future=http.sendAsync(request,info->new LimitedBody());
            var response=future.get(10,TimeUnit.SECONDS);int status=response.statusCode();
            if(status==429)throw new Failure("REMOTE_RATE_LIMIT",status,false,true,retryAfter(response.headers().firstValue("Retry-After").orElse("")));
            if(status==401 || status==403)throw new Failure("REMOTE_AUTH",status,false,false,0);
            if(status==408 || status>=500)throw new Failure("REMOTE_UNAVAILABLE",status,write,true,0);
            if(status>=400 && status<500)throw new Failure("REMOTE_REJECTED",status,false,false,0);
            if(status>=300 || status<200)throw new Failure("REMOTE_REDIRECT_OR_STATUS",status,write,false,0);
            if(method.equals("PUT") && (status==200 || status==204))return json.nullNode();
            if(method.equals("POST") && status!=201)throw invalid(true);
            if(method.equals("GET") && status!=200)throw invalid(false);
            var result=json.readTree(response.body());
            if(result==null || !result.isObject())throw invalid(write);
            return result;
        } catch(Failure e){throw e;}
        catch(InterruptedException e){Thread.currentThread().interrupt();throw new Failure("REMOTE_INTERRUPTED",0,write,true,0);}
        catch(Exception e){throw new Failure("REMOTE_INVALID_OR_TIMEOUT",0,write,true,0);}
        finally{if(future!=null && !future.isDone())future.cancel(true);}
    }
    private static Failure invalid(boolean write){return new Failure("REMOTE_INVALID_RESPONSE",0,write,false,0);}
    static long retryAfter(String value) {
        try{return Math.max(1,Math.min(3600,Long.parseLong(value)));}
        catch(Exception e){try{return Math.max(1,Math.min(3600,Duration.between(Instant.now(),ZonedDateTime.parse(value,DateTimeFormatter.RFC_1123_DATE_TIME).toInstant()).toSeconds()));}catch(Exception ignored){return 30;}}
    }
    private static final class LimitedBody implements HttpResponse.BodySubscriber<byte[]> {
        private final CompletableFuture<byte[]> body=new CompletableFuture<>();
        private final ByteArrayOutputStream bytes=new ByteArrayOutputStream();
        private Flow.Subscription subscription;
        public CompletionStage<byte[]> getBody(){return body;}
        public void onSubscribe(Flow.Subscription value){subscription=value;subscription.request(1);}
        public void onNext(List<ByteBuffer> buffers) {
            for(var buffer:buffers) {
                if(bytes.size()+buffer.remaining()>1048576){subscription.cancel();body.completeExceptionally(new IllegalStateException("Response too large"));return;}
                byte[] part=new byte[buffer.remaining()];buffer.get(part);bytes.writeBytes(part);
            }
            subscription.request(1);
        }
        public void onError(Throwable error){body.completeExceptionally(error);}
        public void onComplete(){body.complete(bytes.toByteArray());}
    }
}
