-- S09: local publication snapshots and delivery metadata; never store tracker credentials.
CREATE TABLE redmine_bindings (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    work_item_id BIGINT NOT NULL,
    correlation_marker CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    instance_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    configuration_json JSON NOT NULL,
    external_issue_id BIGINT NULL,
    create_attempted BOOLEAN NOT NULL DEFAULT FALSE,
    delivered_source_version BIGINT NULL,
    delivered_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    delivered_payload JSON NULL,
    observed_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    observed_payload JSON NULL,
    observed_at DATETIME(6) NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_redmine_binding_work UNIQUE(project_id,work_item_id),
    CONSTRAINT uq_redmine_binding_scope UNIQUE(project_id,work_item_id,id),
    CONSTRAINT uq_redmine_marker UNIQUE(correlation_marker),
    CONSTRAINT uq_redmine_remote UNIQUE(instance_hash,external_issue_id),
    CONSTRAINT fk_redmine_binding_work FOREIGN KEY(project_id,work_item_id) REFERENCES work_items(project_id,id),
    CONSTRAINT fk_redmine_binding_actor FOREIGN KEY(project_id,created_by) REFERENCES project_memberships(project_id,id),
    CONSTRAINT ck_redmine_remote_id CHECK(external_issue_id IS NULL OR external_issue_id>0),
    CONSTRAINT ck_redmine_create_attempted CHECK(create_attempted IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE redmine_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    work_item_id BIGINT NOT NULL,
    binding_id BIGINT NOT NULL,
    operation VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'QUEUED',
    source_version BIGINT NOT NULL,
    payload_json JSON NOT NULL,
    payload_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    expected_remote_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    request_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL,
    dispatch_by BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 5,
    next_attempt_at DATETIME(6) NOT NULL,
    lease_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lease_until DATETIME(6) NULL,
    reconcile_only BOOLEAN NOT NULL DEFAULT FALSE,
    error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    http_status SMALLINT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    active_binding BIGINT GENERATED ALWAYS AS (CASE WHEN status IN ('QUEUED','RUNNING','RETRY_WAIT','UNCERTAIN','CONFLICT') THEN binding_id ELSE NULL END) STORED,
    CONSTRAINT uq_redmine_active UNIQUE(active_binding),
    CONSTRAINT uq_redmine_request UNIQUE(project_id,request_key),
    CONSTRAINT uq_redmine_outbox_scope UNIQUE(project_id,id),
    CONSTRAINT fk_redmine_outbox_binding FOREIGN KEY(project_id,work_item_id,binding_id) REFERENCES redmine_bindings(project_id,work_item_id,id),
    CONSTRAINT fk_redmine_outbox_actor FOREIGN KEY(project_id,created_by) REFERENCES project_memberships(project_id,id),
    CONSTRAINT fk_redmine_outbox_dispatch_actor FOREIGN KEY(project_id,dispatch_by) REFERENCES project_memberships(project_id,id),
    CONSTRAINT ck_redmine_operation CHECK(operation IN ('PUBLISH','RECONCILE')),
    CONSTRAINT ck_redmine_delivery_status CHECK(status IN ('QUEUED','RUNNING','RETRY_WAIT','UNCERTAIN','DELIVERED','FAILED','CONFLICT','SUPERSEDED')),
    CONSTRAINT ck_redmine_attempt_count CHECK(attempt_count>=0 AND max_attempts>0),
    CONSTRAINT ck_redmine_reason CHECK(CHAR_LENGTH(TRIM(reason))>0),
    CONSTRAINT ck_redmine_reconcile CHECK(reconcile_only IN (0,1)),
    INDEX ix_redmine_dispatch(status,next_attempt_at,id),
    INDEX ix_redmine_expired_lease(status,lease_until,id),
    INDEX ix_redmine_work_history(project_id,work_item_id,id)
) ENGINE=InnoDB;

CREATE TABLE redmine_delivery_attempts (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    outbox_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    lease_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    outcome VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    http_status SMALLINT NULL,
    actor_membership_id BIGINT NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    CONSTRAINT uq_redmine_attempt UNIQUE(project_id,outbox_id,lease_key),
    CONSTRAINT fk_redmine_attempt_job FOREIGN KEY(project_id,outbox_id) REFERENCES redmine_outbox(project_id,id),
    CONSTRAINT fk_redmine_attempt_actor FOREIGN KEY(project_id,actor_membership_id) REFERENCES project_memberships(project_id,id),
    CONSTRAINT ck_redmine_attempt_no CHECK(attempt_no>0),
    INDEX ix_redmine_attempt_history(project_id,outbox_id,id)
) ENGINE=InnoDB;
