-- LOCAL DEMO ONLY. Public password @test1234; unique PBKDF2 salt per user.
-- Additive V22; no workbook, result, bug or real personal/asset identifiers.
-- Collision or missing enabled demo administrator rolls back all inserted rows.
START TRANSACTION;
SET @lab_now=UTC_TIMESTAMP(6);
SET @lab_admin=(SELECT id FROM identity_users WHERE username='syp.demo.admin' AND role_code='ADMIN' AND enabled=TRUE);
INSERT INTO identity_users(id,username,display_name,password_hash,role_code,enabled,can_create_users,created_at) VALUES
(UUID(),'syp.lab.pm01','[Demo22] PM 01','{pbkdf2-v5_8}2bc972ba0838a152b334f6f7d0291e1ab7b0baef2ae74595376ed23cab1ad5a6edf31367d3cdaca627bd21881dedb7a1','PM',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.pm02','[Demo22] PM 02','{pbkdf2-v5_8}febc7362147deeebcbb67008f934a2792114f0ed245163fd967ee59378b473f32ba0c00145dc49612786342dd63c9c40','PM',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.pm03','[Demo22] PM 03','{pbkdf2-v5_8}654aa260e57ef895e60eea7355e625acddcc85979068a45e3215ba7b84b9dff5d144d3a24e4b6bf21a934ab94f5ce6c3','PM',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev01','[Demo22] Dev 01','{pbkdf2-v5_8}2ed875663c3b3392c3bbe735f2b307dbd38703e248e8ae6f84f715f3b3374a69ccb9a97e2816b7778f738d077a6ffa3a','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev02','[Demo22] Dev 02','{pbkdf2-v5_8}833f9ffa8182d37c99caecbd94c3e2fca2cfd33d87994ec402927d884c1bf45ac8266d7ef5e54848ac62131f3f22f45d','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev03','[Demo22] Dev 03','{pbkdf2-v5_8}a552061b4033de18e15d67ad31a63616df7b528d35c8f01e357733c5d01505b1ca3436f5e72717d9f4ba1a936230536c','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev04','[Demo22] Dev 04','{pbkdf2-v5_8}44273ad7db3060443fbc74635b4222442734a422565a9c5f921a4076893ad96c8c5960ed926ceb5854abe1f6e5e1bf9f','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev05','[Demo22] Dev 05','{pbkdf2-v5_8}2e92d96ef09d41179d48bacd7511921bfe554aeeab9571765aadf07a55cbdbdafe29dc1e58ae89e19499451cfa16358d','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev06','[Demo22] Dev 06','{pbkdf2-v5_8}aec9ccc9456cc923ba901560032c9ba7b3a1f4f0873b8ef1f63806eb2dad7558aa2af0fee9d9c546590d1794628f1324','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev07','[Demo22] Dev 07','{pbkdf2-v5_8}0d402bfbf96d3eb48f75668846e5c96318eac5525d00011b6dd923ce2728db05fa2ba89d65adfb649b8f5d24231ece90','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev08','[Demo22] Dev 08','{pbkdf2-v5_8}8a338358d469030136c6beb49ec7c4cdbfc0acbfb29c19e7e6b615e7df91d8bae2e7b660fdc90e70dc1fc66e086c2137','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev09','[Demo22] Dev 09','{pbkdf2-v5_8}352a3588f1926882c9a89a551b4c32171685a4444d69259e5f041dd93aae19002aae28a4e5a6dc69f419ed295f7e0d0c','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev10','[Demo22] Dev 10','{pbkdf2-v5_8}cffbd8dd77b2e0ea1821ff508496e2214a0ec37bbab15627cdcd1fa799ef6351541130b9692c0c1fbb0f4ccd89e82a25','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev11','[Demo22] Dev 11','{pbkdf2-v5_8}e59559834229f7077c1f0741af491875e7e6130c333f663f9391a5220c4ed31e3137d4ef40b6e866432447c2e1a5508d','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev12','[Demo22] Dev 12','{pbkdf2-v5_8}e1912319f12b5d3dbc0fef51c19b4afb9459b5167306d2a249c4e2d17d3eab0241595052cf6eeb32c4458a4360ca86a4','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev13','[Demo22] Dev 13','{pbkdf2-v5_8}5129c7cb790ca7979ae9d618de99f82b5ad8d09a558745f3169111c460d6770e24b68fe38752cc5c5d900bfecfc6b006','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev14','[Demo22] Dev 14','{pbkdf2-v5_8}dd24106673017451416b096cfb49ae789585e0139f0525efd4cfa6cb66cfc5b89a34b2fa18317de92528a6cf4c86c4f0','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev15','[Demo22] Dev 15','{pbkdf2-v5_8}c25048b0f3b266a92c2be9bf30f0e91ad9c28614cd0c0d766c9a5262a5f62a37e464435dad131b597f40b0f0bfac539e','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev16','[Demo22] Dev 16','{pbkdf2-v5_8}c379785f2beab7fcce5d13348e0ed8c48f235fdbeb220d0f739285aa7cf998a02943779697fef50b1b0baa785d47f67d','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev17','[Demo22] Dev 17','{pbkdf2-v5_8}4f72a16834df6d57ecfdff28881414704678e5c12940c93d020244e1047d8951416e697a7db44fd34991ff5ddc5f2f2c','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev18','[Demo22] Dev 18','{pbkdf2-v5_8}260a6fe084aa7fd4251153dbf14c133d73e0a78680dac7b8fa56543c33b5f0900f00c001bc0f0813a572861b95f8c51e','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev19','[Demo22] Dev 19','{pbkdf2-v5_8}bdeb6c6d0f4bf81c7e0569ee48f02913d0de7ded7310b2c7821b9537a8ab8cf32a9f45efb3fa612e65ac5b01f6b7eed5','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.dev20','[Demo22] Dev 20','{pbkdf2-v5_8}619547cd7f71fc60d1e96e21c528720a1255d546e79e9397e9ea238360187e31d23dcdc3354b2a98b317ae2302eea002','DEV',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester01','[Demo22] Tester 01','{pbkdf2-v5_8}5c6f8f868c7be8566567f7c045960e564adec92bd05fac164481a2f45f5ec02435742da74af5e1365f9e1741930ce693','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester02','[Demo22] Tester 02','{pbkdf2-v5_8}92829e5382f0ca94610051ee307e62d4b1ccc5ff7d008914350b80ccbbac09aafcc959ebe7f989aa5580358f0c4a4a94','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester03','[Demo22] Tester 03','{pbkdf2-v5_8}d134c0604760b9b9cc5eef14a34153a28e0d6c4291f18031c9ff51e64148806fdac6586f59914fdc8cbd590fa3292adb','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester04','[Demo22] Tester 04','{pbkdf2-v5_8}86bc2e8e2f2f92039957979570aafde06b2edfe6fe7c355c637118855992df6d818b124f0ff318fb738691ef87b5cd4a','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester05','[Demo22] Tester 05','{pbkdf2-v5_8}85f91221a7039e86d8e921d876f9f44ac510082f382deaf18d3077b8b867f919b22dbd467767e0950c3aabcc63e9fa0c','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester06','[Demo22] Tester 06','{pbkdf2-v5_8}93de63deb8c0c3db375379ad6f42b932b208a947f5a7573d96e384651884b415e740995f32b2e6addfa00bf0b28d7c24','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester07','[Demo22] Tester 07','{pbkdf2-v5_8}dbef82e5c81f3479fa4e3f70df84395733fb2ca9fa61896a92aa4056e7a59af4bf6c0000bf97953437d67fdec7163189','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester08','[Demo22] Tester 08','{pbkdf2-v5_8}6204e52b8b2cf9eb832f7f8031e149962fa8a081cd204ebb19dff99c2d2d5a59065f6f7349b99ed1eba067494e757140','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester09','[Demo22] Tester 09','{pbkdf2-v5_8}952d954dd92078f9024c7581d14201d7a028738deb4def411120f42d5e4ce2bd6faedeaeb84d76af1179b42a91d208fa','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester10','[Demo22] Tester 10','{pbkdf2-v5_8}1d8a39faaae97a4a9f8e778209860356e3184ae7cf20c46b7e16cfc3d9d8ec67e429c37dceb387ba96f86390b334fbe9','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester11','[Demo22] Tester 11','{pbkdf2-v5_8}d501c0b0ed067df5914e4c2cf54124f5309fca4bd80eeb62b8311df805989c00c5a71ce6394f954ac7d9969a9a2a23cf','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester12','[Demo22] Tester 12','{pbkdf2-v5_8}d00143abd47f345298b7c956a2f1ae1e7bfd74afc1979b9724eb23d0a9a10f4db1682b7d1668b521f98b248d703bd9c8','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester13','[Demo22] Tester 13','{pbkdf2-v5_8}f30ff25b8509b6b0f0a2717d55884a63668a67bab070bffe86e3221059b66907d5e82497f3f441a3ddb6c22b5c13e85d','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester14','[Demo22] Tester 14','{pbkdf2-v5_8}266de71574eac8d54a98679aebb064f6312f8ac5b671582d471420e7163e74e8efeb9a15a38f3247bc81d0fa05fbb9d9','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester15','[Demo22] Tester 15','{pbkdf2-v5_8}ec9e2f90be2803d76ba89a8cc1130a090bac1b1cb14ec59d2aa9d6d84a228b407f849775981c0322ded066b83fc14e7a','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester16','[Demo22] Tester 16','{pbkdf2-v5_8}68ee62473a5501060488ffa7d26835b90b72a8e7ca73d0a76e8c2b0f878a989ce5a5230327cc03276c84bfebf75ca47e','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester17','[Demo22] Tester 17','{pbkdf2-v5_8}30a90ea1528f53167ec61dcc06eaf16a5ad177391fa46a1ea1dbaf7edc1168d9584356f3a852c0db0f269f693b9b6c3f','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester18','[Demo22] Tester 18','{pbkdf2-v5_8}142cced33b29ea5a404ad8c0ddf9aa13097a35a36f540dab9a7ef6e55eea14e1324e72c68b7ca4b6c810c8e23e3c97e7','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester19','[Demo22] Tester 19','{pbkdf2-v5_8}e114d038b8be5d00f0858026966007316400174f627559920f91d272e079481ad3066e8dfd82f0021769f9f3dc8c4879','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester20','[Demo22] Tester 20','{pbkdf2-v5_8}7da79792817e00094975cdf888e8fc2e5b2c5c31d5531c61307a8b4a98aab369f51a4f729e4e8359c3abdbcf86c70931','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester21','[Demo22] Tester 21','{pbkdf2-v5_8}0256d4129d2db19ca25521d052a4176f180f18d9bc644554bcc369c5d6c488839edd645eb58812fa61d6ed8ac5ec21fc','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester22','[Demo22] Tester 22','{pbkdf2-v5_8}b4b8e5f1c1a434b160ddadd3f19b96d1dead9f7286fed4286c4dfc8b255ed2a0866127ad6e1ac419b1a5faf5f75b166d','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester23','[Demo22] Tester 23','{pbkdf2-v5_8}e095958e88d712a8cd12074a1f14c11e8133b8f7e33e1f3b950b9fd5cb66cfdb69042d6f74e90de519d40239d797ad30','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester24','[Demo22] Tester 24','{pbkdf2-v5_8}dd787bca6bf4d19fbd8be293ea5ad468e08b8c9b72950678711e0cf6e6d0ac7844e6beca9cedb6777792064046104a5d','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester25','[Demo22] Tester 25','{pbkdf2-v5_8}06fae9ccd0688d904ffa02ea1e0fd7dfcab7044652a681bbde74cc0ccccc18beb1f618a5d783dfd6872a95aa072c1cae','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester26','[Demo22] Tester 26','{pbkdf2-v5_8}7e07ae7e7f560cc29764a6e70de1f61f4cf25d2cb21c46a5ea12e04b568191ac7eff5438026e69e1a159f32ebff52be6','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester27','[Demo22] Tester 27','{pbkdf2-v5_8}1836c3c397916e776c18606706c53a8ab9921cc09f03ebfdda9a9d97a67be57d3c799f9557ec5cff658c0ae0ecadb47b','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester28','[Demo22] Tester 28','{pbkdf2-v5_8}9f6ab437865ea9a2672b66007049bc2513dbabd30bdbc1d47126c168894c35de4e3667a7398311c430cee8217ff98b64','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester29','[Demo22] Tester 29','{pbkdf2-v5_8}b0d3c3a50db862a9742cc1d9c9d25d428e106f2eec37301cc9963413199861c08b32f3c7cc2c73a8f29396165e053c8c','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester30','[Demo22] Tester 30','{pbkdf2-v5_8}dff11ba2b3a0f57cc1ea0075ad038734f56f414c93649ff69c3389fc56733631e70b4c07d5b30f8e7c8e83b0c2beabd8','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester31','[Demo22] Tester 31','{pbkdf2-v5_8}2bd221b03bfaace49fb5199579e2ddf00db893bce4dcb46790a908fd7e032f341c4a5ffdfc74ad95fc49a3e02036eb6a','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester32','[Demo22] Tester 32','{pbkdf2-v5_8}47faaef0378b7b493ba94b5f52025c3959d8e70327c4d9c0d79f7ba2c0496f0283cf921941cfe9fc1bc487f02eee31e9','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester33','[Demo22] Tester 33','{pbkdf2-v5_8}bd396287271cee32aee9ce07d262b9ebbdceb674f37899fd76d8ae6a88055fdf0cc4e80234eabe3a6d18495bee29adb9','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester34','[Demo22] Tester 34','{pbkdf2-v5_8}3771743ada7b07ada9da887b13861ef1cd5a3134fef7058af516d8b49d1abea5e99e6d570dcb5d0d6437d48381021f47','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester35','[Demo22] Tester 35','{pbkdf2-v5_8}645275c62b2b014b908f7adbca8e0375157b3e195489f1b683a9cb0dbe5c1a0e48ae04d0957561e9909170b8bda78374','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester36','[Demo22] Tester 36','{pbkdf2-v5_8}d1496cab81da4a212696384bd6f0293f4afc9c59e497733577eb4ca4a571423dc1e04b936764808c358f5fa0fe370734','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester37','[Demo22] Tester 37','{pbkdf2-v5_8}b14805494db85fab0c7335cce7a9a46c4f74957e1a857787c409ffcc123a69c5f0a35a0c43e5dc63d8a6aebca40775f5','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester38','[Demo22] Tester 38','{pbkdf2-v5_8}120289d47111ab362e7e0faa8e1df8e42e836b07da84fe587c812ada6d99b2b3e7fae3463c424abe6d4705b50561bad2','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester39','[Demo22] Tester 39','{pbkdf2-v5_8}6fae48aa4111cc257c7b7803890ab9c34cb87bd6b27e99eb1bb527bed7cbfafe0133281b86f3681e8b2eead72b486798','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester40','[Demo22] Tester 40','{pbkdf2-v5_8}1de64de74734bd00c49132c1e8a256cf1215c20fc8f850e49e5a698f83dbf9cedc6d051c7754d4e04315c6acb10139ae','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester41','[Demo22] Tester 41','{pbkdf2-v5_8}826e8ad80943b1050ca2cde82e5933790ee630604bd7d7c7f8a2321d61caa6f4886d4ea0f046a8b0816f281ba4ce5305','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester42','[Demo22] Tester 42','{pbkdf2-v5_8}f3d3a917cb83989affd5bc6213e041e249f51344d3c04c8b77650a73426e9b6d054436e5f25a2834e676d7ea9be2d34b','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester43','[Demo22] Tester 43','{pbkdf2-v5_8}a6c5d0185ab74dd94c937aacbd68e56e5654f4d5f19e17920816f55fe94295066622a0b25b3eadc6a805e0ba2c315b50','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester44','[Demo22] Tester 44','{pbkdf2-v5_8}f8f2cefffd2da1f538c737b160c08f09096a1964045f1344e0f8daa621eff2bfe4e01dcaccfd11b64d79844dea3cbaa0','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester45','[Demo22] Tester 45','{pbkdf2-v5_8}8939acfe8703e1b845a5f08b122f9af19ffef2a0ffbcfc2843e986bf90385583dcbe3b9679c448a44fab3c0c7f98b99d','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester46','[Demo22] Tester 46','{pbkdf2-v5_8}d008909175858f8c233099a1bd77ac9855abffe44aa6991b7dccee9400a74b4ffcc6ae0530f569567962313f68887621','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester47','[Demo22] Tester 47','{pbkdf2-v5_8}dd8bcb6aa9d8e7e4dcbe4e2dc27f2883c7479df3f46721da5139f8751df4d322aa3e80fe4f0e223be8c4e5354b78a12b','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester48','[Demo22] Tester 48','{pbkdf2-v5_8}3a62193a5bfc3da96dcd19342162025fae82ef4b92b03db608878a7eeedcdee52d463ef94ab1a43d54bede35daa0185b','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester49','[Demo22] Tester 49','{pbkdf2-v5_8}6f77e3df55bd35fd95744c437912300284773fb16b4ff11f62de3829686c2f1f5462c07d7db3b69790479554873da95a','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester50','[Demo22] Tester 50','{pbkdf2-v5_8}b1dcecd6b6abc94578e90aa828c312ee2aac99953d16d5e3e4b1771c195b14c915a7327b8eb44285907c6626a5e9b5ee','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester51','[Demo22] Tester 51','{pbkdf2-v5_8}219df7e3cd1724f17be8a7fba269cf3fed375a17c80d656bde850eb670e427c010c3d6ffb861ec9cf654045948919fbe','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester52','[Demo22] Tester 52','{pbkdf2-v5_8}1e36757f5542546c5651df366204e721afe7c7642f0d92558d27d2716645232c1a08a979bff7f8eadd20f9c8250e4a96','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester53','[Demo22] Tester 53','{pbkdf2-v5_8}466f9ae9a2c04c1f16bdbc5073c4a75e293a6eeda5942a8aa6e201df665e7bb20fbea4ef95afa007592d0a85fc2d27c1','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester54','[Demo22] Tester 54','{pbkdf2-v5_8}75ee328b3e1ea27bd141e347f1f4e3a083667cb6b9b4473fc847490d6d64fa0bcfa94857279545a76caf56ebfea7703c','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester55','[Demo22] Tester 55','{pbkdf2-v5_8}90a353fb6ffa8f73f7ab325f36a398c9c2a36dae0462be8439eb4d20c2d13ee3519379206665add13c207adde0fcde15','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester56','[Demo22] Tester 56','{pbkdf2-v5_8}65943f0ef83bd352902e15ac64198697742c2476761734f82838851eef5ed71000b3be776e4484e80a9e264b831c9f55','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester57','[Demo22] Tester 57','{pbkdf2-v5_8}2a023166f3ff2679823ab8550807aa6b4111363164beb4217fa3f4735558bd2005a1235a529747e88ae54ec7856090c8','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester58','[Demo22] Tester 58','{pbkdf2-v5_8}9c4d8b97fe934bd51b6ea393664d3fcd0b24a0ace4be58e8b2c44c3a43e9b76586fb6f994fbf97c62245b07d0432b166','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester59','[Demo22] Tester 59','{pbkdf2-v5_8}daf1d5c7ae78a0c72bb0752355a3294444128a997bca9301b9106092dcdd9404cc5c5f239dc400a465af2f5a710e672f','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester60','[Demo22] Tester 60','{pbkdf2-v5_8}be75933be2533a44d7f43e577ff0e5a0c3754e54100a4630264ff876bedeacee0343a59c9b482e6f9e58f8c7ccb6f3bd','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester61','[Demo22] Tester 61','{pbkdf2-v5_8}f219084b7c62125997257cac4a6fd0cc102b7ae49363f5ceca2d9a4a60a33199b601cff9946ed89e8865bfa0b2a09a69','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester62','[Demo22] Tester 62','{pbkdf2-v5_8}34e960c1d9517898d69cf29013f0337825aeb023e79f2ae2597559fc5703fa51380135cd8fd80dfaaca9d5cfc393374a','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester63','[Demo22] Tester 63','{pbkdf2-v5_8}909a38cf533551a734b47f0dc27ee104004e770eb4264af176b57e5f52a35c74ba43a6de99bbdec08c51f43754bae6b3','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester64','[Demo22] Tester 64','{pbkdf2-v5_8}0b5df7bba332c448fc0aceed8a919ef67790019968a7c482b3a12508164b6614d7e0bdf2b8022bb1a0b58727c6726a62','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester65','[Demo22] Tester 65','{pbkdf2-v5_8}2e5bca56738b1c1f806b960e9ad0bc4376b4df8e2ffc65622cfbe227f2824c4fa3cd1f68160b30b014c5b02d4dea99fc','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester66','[Demo22] Tester 66','{pbkdf2-v5_8}c48401a4d9acf19703052d256911c7a176c7a6023b7b910106cb9f9d26c1677afa51be60688351e733c144d37ca1c3e7','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester67','[Demo22] Tester 67','{pbkdf2-v5_8}0ea1722231a0d63dc0f8be8f0c2e1e3c28f13b0c5f90e13d8c8623dfdbd91375df28a5380ac0d4702dff12ffec231ae1','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester68','[Demo22] Tester 68','{pbkdf2-v5_8}4f93ace28b9d9d5433ede04ecab8013d50bd20822f2385fc64e488d8734375f1c8b956bd61b0fd6d5ba0e9ece6c6b84c','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester69','[Demo22] Tester 69','{pbkdf2-v5_8}f2b305233b8c61219462c0714e4f0614c940ed7e7c59104627e36fcf925e0e49dd6662dbc2b548928ecce41710a2630a','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester70','[Demo22] Tester 70','{pbkdf2-v5_8}6826cc0e25f88d4d792ea53ffb0c9a651a2f597167c6584cf4f542f2113658d8cfe39a0217c99d063c7da4ed1398f6b5','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester71','[Demo22] Tester 71','{pbkdf2-v5_8}f1a8b8003661bf9bbb8d2b38fe237834433a02d0393efc723c02fe24192fa267b6d2ea20d7eff1f837408d91c786d403','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester72','[Demo22] Tester 72','{pbkdf2-v5_8}b0f1a2f2c073614bea1fc80001c184a40256476e85f903bd62285a5cef767fb95f1e6121e1b5290dc1062a6ae502bf39','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester73','[Demo22] Tester 73','{pbkdf2-v5_8}c00e3f9a37e5d941686c5a4db19bbb0e54fb7bc12d8b63d4a26121ce1c4efc83514f3924e4bcf982d8237c77219b76e9','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester74','[Demo22] Tester 74','{pbkdf2-v5_8}f96ead336a181f7dded9e136888f03acfebc6f511069734691518936353388ab88c9a37b61e7218479bc3b8f894c235e','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester75','[Demo22] Tester 75','{pbkdf2-v5_8}ef61fd160a576a37aff05c512fbea37f6e05184629037117a057611f886cc08a2a37bcf614e4c48d56b86d7a24446a67','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester76','[Demo22] Tester 76','{pbkdf2-v5_8}b2a89700e2f80f4c999ede52da0fc847cf51bcb67d0756b02e2313fc759b62921d6819233e0103013779b8748bf80a10','TESTER',TRUE,FALSE,@lab_now),
(UUID(),'syp.lab.tester77','[Demo22] Tester 77','{pbkdf2-v5_8}7c0e9ba2b4f8f39715b08b40a3043485d3ef92a782e8467d1fdd047f83c47a3ec140255cda19b18d3093d5e9d5196adc','TESTER',TRUE,FALSE,@lab_now);
INSERT INTO projects(code,name,description,created_at,created_by,updated_at,updated_by) VALUES('SYP-LAB-22-IOS','[Demo22] Kiểm thử iPad và iPhone','Dữ liệu DEMO V22, không phải dự án khách hàng. PM nhập file test case để thực hành.',@lab_now,@lab_admin,@lab_now,@lab_admin);
SET @lab_p1=LAST_INSERT_ID();
INSERT INTO project_memberships(project_id,user_id,project_role,created_at,updated_at)
SELECT @lab_p1,id,role_code,@lab_now,@lab_now FROM identity_users WHERE username IN ('syp.lab.pm01','syp.lab.dev01','syp.lab.dev02','syp.lab.dev03','syp.lab.dev04','syp.lab.dev05','syp.lab.dev06','syp.lab.dev07','syp.lab.tester01','syp.lab.tester02','syp.lab.tester03','syp.lab.tester04','syp.lab.tester05','syp.lab.tester06','syp.lab.tester07','syp.lab.tester08','syp.lab.tester09','syp.lab.tester10','syp.lab.tester11','syp.lab.tester12','syp.lab.tester13','syp.lab.tester14','syp.lab.tester15','syp.lab.tester16','syp.lab.tester17','syp.lab.tester18','syp.lab.tester19','syp.lab.tester20','syp.lab.tester21','syp.lab.tester22','syp.lab.tester23','syp.lab.tester24','syp.lab.tester25','syp.lab.tester26');
INSERT INTO environments(project_id,code,name,description,created_at,updated_at) VALUES(@lab_p1,'QA','QA demo','Môi trường kiểm thử giả lập V22',@lab_now,@lab_now);
INSERT INTO builds(project_id,version_label,build_number,platform,notes,released_at,created_at,updated_at) VALUES
(@lab_p1,'1.0.0','LAB-1','iOS','Build DEMO ban đầu',DATE(@lab_now),@lab_now,@lab_now),
(@lab_p1,'1.0.1','LAB-2','iOS','Build DEMO kiểm thử lại',DATE(@lab_now),@lab_now,@lab_now);
INSERT INTO categories(project_id,code,name,created_at,updated_at) VALUES(@lab_p1,'FUNCTIONAL','Chức năng',@lab_now,@lab_now),(@lab_p1,'UI','Giao diện',@lab_now,@lab_now);
INSERT INTO devices(project_id,code,name,model,os_name,os_version,created_at,updated_at) VALUES
(@lab_p1,'IPAD','iPad đa phiên bản','iPad','iPadOS','Đa phiên bản',@lab_now,@lab_now),
(@lab_p1,'IPHONE','iPhone đa phiên bản','iPhone','iOS','Đa phiên bản',@lab_now,@lab_now);
INSERT INTO milestones(project_id,code,name,starts_on,due_on,created_at,updated_at) VALUES(@lab_p1,'LAB-RELEASE','Mốc kiểm thử DEMO',DATE(@lab_now),DATE_ADD(DATE(@lab_now),INTERVAL 30 DAY),@lab_now,@lab_now);
INSERT INTO test_cycles(project_id,code,name,milestone_id,created_at,created_by)
SELECT @lab_p1,'LAB-C1','Đợt kiểm thử DEMO',m.id,@lab_now,u.id FROM milestones m JOIN project_memberships u ON u.project_id=m.project_id AND u.project_role='PM' WHERE m.project_id=@lab_p1 AND m.code='LAB-RELEASE';
INSERT INTO cycle_configurations(project_id,cycle_id,environment_id,device_id,default_build_id,created_at)
SELECT @lab_p1,c.id,e.id,d.id,b.id,@lab_now FROM test_cycles c JOIN environments e ON e.project_id=c.project_id AND e.code='QA' JOIN devices d ON d.project_id=c.project_id JOIN builds b ON b.project_id=c.project_id AND b.build_number='LAB-1' WHERE c.project_id=@lab_p1 AND c.code='LAB-C1';
INSERT INTO projects(code,name,description,created_at,created_by,updated_at,updated_by) VALUES('SYP-LAB-22-TABLET','[Demo22] Kiểm thử tablet Android','Dữ liệu DEMO V22, không phải dự án khách hàng. PM nhập file test case để thực hành.',@lab_now,@lab_admin,@lab_now,@lab_admin);
SET @lab_p2=LAST_INSERT_ID();
INSERT INTO project_memberships(project_id,user_id,project_role,created_at,updated_at)
SELECT @lab_p2,id,role_code,@lab_now,@lab_now FROM identity_users WHERE username IN ('syp.lab.pm02','syp.lab.dev08','syp.lab.dev09','syp.lab.dev10','syp.lab.dev11','syp.lab.dev12','syp.lab.dev13','syp.lab.dev14','syp.lab.tester27','syp.lab.tester28','syp.lab.tester29','syp.lab.tester30','syp.lab.tester31','syp.lab.tester32','syp.lab.tester33','syp.lab.tester34','syp.lab.tester35','syp.lab.tester36','syp.lab.tester37','syp.lab.tester38','syp.lab.tester39','syp.lab.tester40','syp.lab.tester41','syp.lab.tester42','syp.lab.tester43','syp.lab.tester44','syp.lab.tester45','syp.lab.tester46','syp.lab.tester47','syp.lab.tester48','syp.lab.tester49','syp.lab.tester50','syp.lab.tester51','syp.lab.tester52');
INSERT INTO environments(project_id,code,name,description,created_at,updated_at) VALUES(@lab_p2,'QA','QA demo','Môi trường kiểm thử giả lập V22',@lab_now,@lab_now);
INSERT INTO builds(project_id,version_label,build_number,platform,notes,released_at,created_at,updated_at) VALUES
(@lab_p2,'1.0.0','LAB-1','Android','Build DEMO ban đầu',DATE(@lab_now),@lab_now,@lab_now),
(@lab_p2,'1.0.1','LAB-2','Android','Build DEMO kiểm thử lại',DATE(@lab_now),@lab_now,@lab_now);
INSERT INTO categories(project_id,code,name,created_at,updated_at) VALUES(@lab_p2,'FUNCTIONAL','Chức năng',@lab_now,@lab_now),(@lab_p2,'UI','Giao diện',@lab_now,@lab_now);
INSERT INTO devices(project_id,code,name,model,os_name,os_version,created_at,updated_at) VALUES
(@lab_p2,'TABLET','Tablet Android đa phiên bản','Tablet Android','Android','Đa phiên bản',@lab_now,@lab_now);
INSERT INTO milestones(project_id,code,name,starts_on,due_on,created_at,updated_at) VALUES(@lab_p2,'LAB-RELEASE','Mốc kiểm thử DEMO',DATE(@lab_now),DATE_ADD(DATE(@lab_now),INTERVAL 30 DAY),@lab_now,@lab_now);
INSERT INTO test_cycles(project_id,code,name,milestone_id,created_at,created_by)
SELECT @lab_p2,'LAB-C1','Đợt kiểm thử DEMO',m.id,@lab_now,u.id FROM milestones m JOIN project_memberships u ON u.project_id=m.project_id AND u.project_role='PM' WHERE m.project_id=@lab_p2 AND m.code='LAB-RELEASE';
INSERT INTO cycle_configurations(project_id,cycle_id,environment_id,device_id,default_build_id,created_at)
SELECT @lab_p2,c.id,e.id,d.id,b.id,@lab_now FROM test_cycles c JOIN environments e ON e.project_id=c.project_id AND e.code='QA' JOIN devices d ON d.project_id=c.project_id JOIN builds b ON b.project_id=c.project_id AND b.build_number='LAB-1' WHERE c.project_id=@lab_p2 AND c.code='LAB-C1';
INSERT INTO projects(code,name,description,created_at,created_by,updated_at,updated_by) VALUES('SYP-LAB-22-PHONE','[Demo22] Kiểm thử smartphone Android','Dữ liệu DEMO V22, không phải dự án khách hàng. PM nhập file test case để thực hành.',@lab_now,@lab_admin,@lab_now,@lab_admin);
SET @lab_p3=LAST_INSERT_ID();
INSERT INTO project_memberships(project_id,user_id,project_role,created_at,updated_at)
SELECT @lab_p3,id,role_code,@lab_now,@lab_now FROM identity_users WHERE username IN ('syp.lab.pm03','syp.lab.dev15','syp.lab.dev16','syp.lab.dev17','syp.lab.dev18','syp.lab.dev19','syp.lab.dev20','syp.lab.tester53','syp.lab.tester54','syp.lab.tester55','syp.lab.tester56','syp.lab.tester57','syp.lab.tester58','syp.lab.tester59','syp.lab.tester60','syp.lab.tester61','syp.lab.tester62','syp.lab.tester63','syp.lab.tester64','syp.lab.tester65','syp.lab.tester66','syp.lab.tester67','syp.lab.tester68','syp.lab.tester69','syp.lab.tester70','syp.lab.tester71','syp.lab.tester72','syp.lab.tester73','syp.lab.tester74','syp.lab.tester75','syp.lab.tester76','syp.lab.tester77');
INSERT INTO environments(project_id,code,name,description,created_at,updated_at) VALUES(@lab_p3,'QA','QA demo','Môi trường kiểm thử giả lập V22',@lab_now,@lab_now);
INSERT INTO builds(project_id,version_label,build_number,platform,notes,released_at,created_at,updated_at) VALUES
(@lab_p3,'1.0.0','LAB-1','Android','Build DEMO ban đầu',DATE(@lab_now),@lab_now,@lab_now),
(@lab_p3,'1.0.1','LAB-2','Android','Build DEMO kiểm thử lại',DATE(@lab_now),@lab_now,@lab_now);
INSERT INTO categories(project_id,code,name,created_at,updated_at) VALUES(@lab_p3,'FUNCTIONAL','Chức năng',@lab_now,@lab_now),(@lab_p3,'UI','Giao diện',@lab_now,@lab_now);
INSERT INTO devices(project_id,code,name,model,os_name,os_version,created_at,updated_at) VALUES
(@lab_p3,'PHONE','Smartphone Android đa phiên bản','Smartphone Android','Android','Đa phiên bản',@lab_now,@lab_now);
INSERT INTO milestones(project_id,code,name,starts_on,due_on,created_at,updated_at) VALUES(@lab_p3,'LAB-RELEASE','Mốc kiểm thử DEMO',DATE(@lab_now),DATE_ADD(DATE(@lab_now),INTERVAL 30 DAY),@lab_now,@lab_now);
INSERT INTO test_cycles(project_id,code,name,milestone_id,created_at,created_by)
SELECT @lab_p3,'LAB-C1','Đợt kiểm thử DEMO',m.id,@lab_now,u.id FROM milestones m JOIN project_memberships u ON u.project_id=m.project_id AND u.project_role='PM' WHERE m.project_id=@lab_p3 AND m.code='LAB-RELEASE';
INSERT INTO cycle_configurations(project_id,cycle_id,environment_id,device_id,default_build_id,created_at)
SELECT @lab_p3,c.id,e.id,d.id,b.id,@lab_now FROM test_cycles c JOIN environments e ON e.project_id=c.project_id AND e.code='QA' JOIN devices d ON d.project_id=c.project_id JOIN builds b ON b.project_id=c.project_id AND b.build_number='LAB-1' WHERE c.project_id=@lab_p3 AND c.code='LAB-C1';
INSERT INTO device_assets(asset_code,type,model,serial,os_name,os_version,condition_code,notes,created_at,created_by,updated_at,updated_by) VALUES
('SYP-LAB-22-IPAD-01','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-01','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-02','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-02','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-03','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-03','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-04','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-04','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-05','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-05','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-06','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-06','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-07','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-07','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-08','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-08','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-09','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-09','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-10','IPAD','Apple iPad (8th generation)','DEMO22-IPAD-10','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 128 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-11','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-11','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-12','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-12','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-13','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-13','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-14','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-14','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-15','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-15','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-16','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-16','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-17','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-17','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-18','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-18','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-19','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-19','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-20','IPAD','Apple iPad (9th generation)','DEMO22-IPAD-20','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 256 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-21','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-21','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-22','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-22','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-23','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-23','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-24','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-24','iPadOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-25','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-25','iPadOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-26','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-26','iPadOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPAD-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-27','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-27','iPadOS','18.0','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-28','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-28','iPadOS','16.6','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-29','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-29','iPadOS','17.5.1','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPAD-30','IPAD','Apple iPad Air (4th generation)','DEMO22-IPAD-30','iPadOS','18.0','RETIRED','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPAD. Bộ nhớ: 64 GB. Màu: Bạc. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho lưu trữ. Ngừng dùng DEMO: máy dành kiểm thử trạng thái lưu trữ. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-01','IPHONE','Apple iPhone 11','DEMO22-IPHONE-01','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-02','IPHONE','Apple iPhone 11','DEMO22-IPHONE-02','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-03','IPHONE','Apple iPhone 11','DEMO22-IPHONE-03','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-04','IPHONE','Apple iPhone 11','DEMO22-IPHONE-04','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-05','IPHONE','Apple iPhone 11','DEMO22-IPHONE-05','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-06','IPHONE','Apple iPhone 11','DEMO22-IPHONE-06','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-07','IPHONE','Apple iPhone 11','DEMO22-IPHONE-07','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-08','IPHONE','Apple iPhone 11','DEMO22-IPHONE-08','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-09','IPHONE','Apple iPhone 11','DEMO22-IPHONE-09','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-10','IPHONE','Apple iPhone 11','DEMO22-IPHONE-10','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-11','IPHONE','Apple iPhone 12','DEMO22-IPHONE-11','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-12','IPHONE','Apple iPhone 12','DEMO22-IPHONE-12','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-13','IPHONE','Apple iPhone 12','DEMO22-IPHONE-13','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-14','IPHONE','Apple iPhone 12','DEMO22-IPHONE-14','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-15','IPHONE','Apple iPhone 12','DEMO22-IPHONE-15','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-16','IPHONE','Apple iPhone 12','DEMO22-IPHONE-16','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-17','IPHONE','Apple iPhone 12','DEMO22-IPHONE-17','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-18','IPHONE','Apple iPhone 12','DEMO22-IPHONE-18','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-19','IPHONE','Apple iPhone 12','DEMO22-IPHONE-19','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-20','IPHONE','Apple iPhone 12','DEMO22-IPHONE-20','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 128 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-21','IPHONE','Apple iPhone 13','DEMO22-IPHONE-21','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-22','IPHONE','Apple iPhone 13','DEMO22-IPHONE-22','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-23','IPHONE','Apple iPhone 13','DEMO22-IPHONE-23','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-24','IPHONE','Apple iPhone 13','DEMO22-IPHONE-24','iOS','18.0','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-25','IPHONE','Apple iPhone 13','DEMO22-IPHONE-25','iOS','16.6','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-26','IPHONE','Apple iPhone 13','DEMO22-IPHONE-26','iOS','17.5.1','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ IPHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-27','IPHONE','Apple iPhone 13','DEMO22-IPHONE-27','iOS','18.0','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-28','IPHONE','Apple iPhone 13','DEMO22-IPHONE-28','iOS','16.6','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-29','IPHONE','Apple iPhone 13','DEMO22-IPHONE-29','iOS','17.5.1','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-IPHONE-30','IPHONE','Apple iPhone 13','DEMO22-IPHONE-30','iOS','18.0','RETIRED','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: IPHONE. Bộ nhớ: 256 GB. Màu: Đen. Kết nối: Wi-Fi / cellular; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho lưu trữ. Ngừng dùng DEMO: máy dành kiểm thử trạng thái lưu trữ. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-01','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-01','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-02','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-02','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-03','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-03','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-04','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-04','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-05','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-05','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-06','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-06','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-07','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-07','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-08','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-08','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-09','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-09','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-10','ANDROID','Samsung Galaxy Tab S8','DEMO22-TABLET-10','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-11','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-11','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-12','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-12','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-13','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-13','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-14','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-14','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-15','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-15','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-16','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-16','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-17','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-17','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-18','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-18','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-19','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-19','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-20','ANDROID','Samsung Galaxy Tab S8+','DEMO22-TABLET-20','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-21','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-21','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-22','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-22','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-23','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-23','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-24','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-24','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-25','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-25','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-26','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-26','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ TABLET-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-27','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-27','Android','14','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-28','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-28','Android','12','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-29','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-29','Android','13','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-TABLET-30','ANDROID','Samsung Galaxy Tab S8 Ultra','DEMO22-TABLET-30','Android','14','RETIRED','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Tablet Android. Bộ nhớ: 128 GB. Màu: Graphite. Kết nối: Wi-Fi. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho lưu trữ. Ngừng dùng DEMO: máy dành kiểm thử trạng thái lưu trữ. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-01','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-01','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-02','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-02','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-03','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-03','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-04','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-04','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-05','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-05','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-06','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-06','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Đã bàn giao cho Tester demo. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-07','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-07','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-08','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-08','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-09','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-09','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-10','ANDROID','Samsung Galaxy S21 5G','DEMO22-PHONE-10','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-1. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-11','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-11','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-12','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-12','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-13','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-13','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-14','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-14','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-15','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-15','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-16','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-16','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-17','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-17','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-18','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-18','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-19','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-19','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-20','ANDROID','Samsung Galaxy S21+ 5G','DEMO22-PHONE-20','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-2. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-21','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-21','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-22','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-22','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-23','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-23','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-24','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-24','Android','14','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-25','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-25','Android','12','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-26','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-26','Android','13','AVAILABLE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho QA, kệ PHONE-3. Máy DEMO sẵn sàng kiểm thử. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-27','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-27','Android','14','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-28','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-28','Android','12','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-29','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-29','Android','13','MAINTENANCE','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Khu bảo trì. Đang bảo trì DEMO: kiểm tra pin và cổng sạc. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin),
('SYP-LAB-22-PHONE-30','ANDROID','Samsung Galaxy S21 Ultra 5G','DEMO22-PHONE-30','Android','14','RETIRED','DEMO — thông tin tài sản giả lập, không phải kiểm kê máy thật. Nhóm: Smartphone Android. Bộ nhớ: 128 GB. Màu: Xám/đen giả lập. Kết nối: Wi-Fi / 5G; SIM demo chưa kích hoạt. Phụ kiện: cáp sạc, ốp bảo vệ. Vị trí: Kho lưu trữ. Ngừng dùng DEMO: máy dành kiểm thử trạng thái lưu trữ. Phiên bản OS là ảnh chụp cấu hình test giả lập, không phải khuyến nghị cập nhật.',@lab_now,@lab_admin,@lab_now,@lab_admin);
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester01' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPAD-01';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester02' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPAD-02';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester03' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPAD-03';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester04' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPAD-04';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester05' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPAD-05';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester06' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPAD-06';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester07' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPHONE-01';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester08' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPHONE-02';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester09' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPHONE-03';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester10' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPHONE-04';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester11' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPHONE-05';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p1,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester12' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p1 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-IPHONE-06';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p2,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester27' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p2 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-TABLET-01';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p2,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester28' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p2 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-TABLET-02';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p2,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester29' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p2 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-TABLET-03';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p2,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester30' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p2 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-TABLET-04';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p2,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester31' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p2 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-TABLET-05';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p2,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester32' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p2 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-TABLET-06';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p3,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester53' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p3 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-PHONE-01';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p3,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester54' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p3 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-PHONE-02';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p3,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester55' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p3 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-PHONE-03';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p3,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester56' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p3 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-PHONE-04';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p3,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester57' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p3 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-PHONE-05';
INSERT INTO device_allocations(asset_id,project_id,recipient_membership_id,assigned_at,assigned_by,expected_return_on,handover_note)
SELECT d.id,@lab_p3,m.id,@lab_now,@lab_admin,DATE_ADD(DATE(@lab_now),INTERVAL 14 DAY),'Bàn giao DEMO V22: đủ cáp sạc và ốp; không phải bàn giao tài sản thật' FROM device_assets d JOIN identity_users u ON u.username='syp.lab.tester58' JOIN project_memberships m ON m.user_id=u.id AND m.project_id=@lab_p3 AND m.project_role='TESTER' AND m.active=TRUE WHERE d.asset_code='SYP-LAB-22-PHONE-06';
INSERT INTO identity_audit(id,actor_id,subject_id,event_code,request_id,occurred_at) SELECT UUID(),@lab_admin,id,'DEMO_SEED','flyway-v22-local',@lab_now FROM identity_users WHERE username LIKE 'syp.lab.%';
INSERT INTO project_audit(project_id,actor_id,entity_type,entity_id,action,occurred_at) SELECT id,@lab_admin,'PROJECT',id,'DEMO_SEED',@lab_now FROM projects WHERE id IN (@lab_p1,@lab_p2,@lab_p3);
INSERT INTO project_audit(project_id,actor_id,entity_type,entity_id,action,occurred_at) SELECT project_id,@lab_admin,'MEMBERSHIP',id,'DEMO_SEED',@lab_now FROM project_memberships WHERE project_id IN (@lab_p1,@lab_p2,@lab_p3);
INSERT INTO project_audit(project_id,actor_id,entity_type,entity_id,action,occurred_at) SELECT NULL,@lab_admin,'DEVICE_ASSET',id,'DEMO_SEED',@lab_now FROM device_assets WHERE asset_code LIKE 'SYP-LAB-22-%';
INSERT INTO project_audit(project_id,actor_id,entity_type,entity_id,action,occurred_at) SELECT project_id,@lab_admin,'DEVICE_ALLOCATION',id,'DEMO_SEED',@lab_now FROM device_allocations WHERE project_id IN (@lab_p1,@lab_p2,@lab_p3);
COMMIT;
