#!/bin/sh
set -eu
# Passwords generated as hex by Initialize-Local.ps1: safe SQL interpolation.
case "$TMS_DB_PASSWORD:$TMS_MIGRATION_PASSWORD" in
  *[!a-fA-F0-9:]*|:*) echo 'Use hex local passwords generated by Initialize-Local.ps1' >&2; exit 1;;
esac
MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mysql -u root <<SQL
CREATE USER 'tms_app'@'%' IDENTIFIED BY '$TMS_DB_PASSWORD';
CREATE USER 'tms_migrator'@'%' IDENTIFIED BY '$TMS_MIGRATION_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON tms.* TO 'tms_app'@'%';
GRANT ALL PRIVILEGES ON tms.* TO 'tms_migrator'@'%';
SQL
