export const statuses = [
  { id: "open", label: "Chưa xử lý", color: "#ed807d", count: 395 },
  { id: "progress", label: "Đang xử lý", color: "#5185bc", count: 55 },
  { id: "recheck", label: "SYP kiểm tra lại", color: "#e97443", count: 0 },
  {
    id: "clarify",
    label: "Xác nhận đặc tả / mức độ",
    color: "#e97443",
    count: 25,
  },
  { id: "ready", label: "Sẵn sàng xử lý", color: "#dc79a0", count: 90 },
  { id: "planning", label: "Lập kế hoạch", color: "#449db5", count: 94 },
  { id: "resolved", label: "Đã xử lý", color: "#5aafa3", count: 13 },
  {
    id: "unreproducible",
    label: "Không tái hiện",
    color: "#9bb143",
    count: 300,
  },
  { id: "wontfix", label: "Không xử lý", color: "#9bb143", count: 1101 },
  { id: "closed", label: "Hoàn thành", color: "#9bb143", count: 3934 },
];
export const members = [
  { name: "SYP Huyen", initials: "H", color: "#f4475d" },
  { name: "SYP My", initials: "M", color: "#4c80ef" },
  { name: "Đỗ Cẩm Nhung", initials: "N", color: "#817ca8" },
  { name: "Nguyễn Giáp", initials: "G", color: "#35a58e" },
  { name: "Phan Quốc Khánh", initials: "K", color: "#ce6179" },
  { name: "Lê Hoàng Nam", initials: "L", color: "#528d58" },
];
export const categories = [
  "Chức năng tiêu chuẩn",
  "Quản lý chỉ dẫn",
  "Bản đồ",
  "Chụp ảnh",
  "Báo cáo",
  "Giao diện",
];
export const milestones = [
  "1.2.0 (Phát hành)",
  "1.2.0(139)",
  "1.2.0(137)",
  "[SPIDER+] 1.1.0 (Phát hành)",
  "1.2.0(131) / 1.2.0-dev(705)",
  "1.2.0(126)",
];
export const versions = [
  "1.2.0(123)",
  "1.2.0(137)",
  "1.2.0(88)",
  "1.0.0(118)",
  "1.0.0(186)",
];
export const types = ["Lỗi", "Yêu cầu", "Công việc", "Cải tiến"];
export const closureReasons = [
  "Đã khắc phục",
  "Không xử lý",
  "Không hợp lệ",
  "Trùng lặp",
  "Không tái hiện",
];
const seeds = [
  [
    6071,
    "【Xuất báo cáo】Danh sách ảnh chỉ dẫn đã sao chép không được xuất ra PDF",
    "ready",
    0,
    "Lỗi",
    "Báo cáo",
  ],
  [
    5863,
    "【Android】【Camera / Con dấu】Đường phân cách của bảng đen không hiển thị trên camera và con dấu",
    "resolved",
    0,
    "Lỗi",
    "Chức năng tiêu chuẩn",
  ],
  [
    6112,
    "【Chỉnh sửa ghi chú】Góc dưới bên trái của phần đầu màn hình không bo tròn theo thiết kế",
    "ready",
    4,
    "Lỗi",
    "Giao diện",
  ],
  [
    2114,
    "【Chi tiết chỉ dẫn】Nút đóng và tùy chọn thêm ảnh hiển thị khác với thiết kế",
    "ready",
    4,
    "Lỗi",
    "Quản lý chỉ dẫn",
  ],
  [
    2104,
    "【Phân loại kiểm tra】Màu ô chọn và đường viền chân trang trong danh sách không đúng",
    "ready",
    4,
    "Lỗi",
    "Quản lý chỉ dẫn",
  ],
  [
    2028,
    "【Chi tiết bản vẽ】Sau khi xóa toàn bộ chỉ dẫn, vùng trạng thái không hiển thị “Không có dữ liệu”",
    "ready",
    4,
    "Lỗi",
    "Quản lý chỉ dẫn",
  ],
  [
    2126,
    "【Vị trí】Dấu ba chấm không xuất hiện khi nội dung nhập vượt quá 128 ký tự",
    "ready",
    5,
    "Lỗi",
    "Quản lý chỉ dẫn",
  ],
  [
    4060,
    "【Danh sách ghi chú】Dấu chấm đỏ không xuất hiện khi ghi chú trên máy chủ được cập nhật",
    "progress",
    2,
    "Lỗi",
    "Chức năng tiêu chuẩn",
  ],
  [
    5829,
    "【Độ phân giải ảnh】Ảnh chụp từ điện thoại tải về máy tính bị thay đổi tỷ lệ",
    "resolved",
    0,
    "Lỗi",
    "Chụp ảnh",
  ],
  [
    5269,
    "【iPad / iPhone】Áp dụng cấu hình số lượng ảnh cho ứng dụng mới",
    "planning",
    1,
    "Yêu cầu",
    "Chụp ảnh",
  ],
  [
    6131,
    "【Chức năng tiêu chuẩn】Bổ sung tìm kiếm thư mục hiện trường, lịch sử và đánh dấu yêu thích",
    "open",
    3,
    "Yêu cầu",
    "Chức năng tiêu chuẩn",
  ],
  [
    6130,
    "【Chức năng tiêu chuẩn】Cấp quyền chia sẻ ghi chú khi liên kết với ứng dụng mới",
    "open",
    3,
    "Yêu cầu",
    "Chức năng tiêu chuẩn",
  ],
  [
    6128,
    "【Đo độ dốc】Hỗ trợ kết nối Bluetooth với các thiết bị ngoài danh sách tiêu chuẩn",
    "open",
    5,
    "Yêu cầu",
    "Chức năng tiêu chuẩn",
  ],
  [
    6127,
    "【Đo độ dốc】Thêm khoảng trắng trước và sau giá trị góc đo cần thiết",
    "open",
    5,
    "Yêu cầu",
    "Chức năng tiêu chuẩn",
  ],
  [
    6119,
    "【Ứng dụng】Thời gian cập nhật ghi chú bản vẽ bị lệch trong kiểm tra thiết bị",
    "open",
    1,
    "Lỗi",
    "Bản đồ",
  ],
  [
    6090,
    "【Bản đồ】Bổ sung bộ lọc vị trí theo từng nhóm công việc",
    "open",
    3,
    "Yêu cầu",
    "Bản đồ",
  ],
  [
    6126,
    "【Xem tài liệu】Tổng hợp lỗi hiển thị tệp MS Office: cắt chữ, thiếu số trang và sai màu",
    "progress",
    3,
    "Lỗi",
    "Chức năng tiêu chuẩn",
  ],
  [
    6123,
    "【Quản lý chỉ dẫn】Chỉ dẫn đã xóa khi ngoại tuyến xuất hiện lại sau khi đồng bộ",
    "progress",
    1,
    "Lỗi",
    "Quản lý chỉ dẫn",
  ],
  [
    6121,
    "【Ảnh công trường】Số lượng ảnh hiển thị ít hơn thực tế sau khi tự động đồng bộ",
    "progress",
    3,
    "Lỗi",
    "Chụp ảnh",
  ],
  [
    6120,
    "【Đo nhiệt độ】Màn hình không hiển thị nhiệt độ sau khi dữ liệu được cập nhật",
    "progress",
    1,
    "Lỗi",
    "Chức năng tiêu chuẩn",
  ],
  [
    6101,
    "【Bản vẽ】Danh sách không cập nhật khi di chuyển tài liệu sang thư mục khác",
    "progress",
    3,
    "Lỗi",
    "Bản đồ",
  ],
  [
    6055,
    "【Ảnh công trường】Không hiển thị hộp thoại xác nhận khi vuốt đóng màn hình đang chỉnh sửa",
    "clarify",
    3,
    "Lỗi",
    "Chụp ảnh",
  ],
  [
    5943,
    "【Ghi chú bản vẽ】Bổ sung nút đóng cho ô nhập ghi chú",
    "clarify",
    5,
    "Yêu cầu",
    "Bản đồ",
  ],
  [
    5897,
    "【Điện thoại】【Camera】Thanh công cụ vẫn hiển thị sau khi đổi số thứ tự",
    "clarify",
    5,
    "Lỗi",
    "Chụp ảnh",
  ],
  [
    5845,
    "【iPad】Không thể khôi phục dữ liệu ảnh công trường do thiếu thông tin máy chủ",
    "clarify",
    4,
    "Lỗi",
    "Chụp ảnh",
  ],
  [
    6129,
    "Tắt tự động đồng bộ theo mặc định và hiển thị thông báo lưu ý khi bật lại",
    "ready",
    3,
    "Yêu cầu",
    "Chức năng tiêu chuẩn",
  ],
  [
    6098,
    "【Bản đồ】Không tái hiện lỗi mất điểm đánh dấu trên phiên bản mới",
    "unreproducible",
    0,
    "Lỗi",
    "Bản đồ",
  ],
  [
    6032,
    "【Giao diện】Giữ cách hiển thị hiện tại theo đặc tả đã thống nhất",
    "wontfix",
    2,
    "Yêu cầu",
    "Giao diện",
  ],
  [
    6091,
    "【Chỉ dẫn / Ghi chú】Ứng dụng bị đóng khi xóa thẻ ghi chú trong danh sách chưa đồng bộ",
    "closed",
    0,
    "Lỗi",
    "Quản lý chỉ dẫn",
  ],
];
export const initialWorkIssues = seeds.map(
  ([number, title, status, person, type, category], index) => ({
    id: `SFLUTTER-${number}`,
    title,
    status,
    assignee: members[person].name,
    type,
    category,
    milestone: index % 5 === 0 || index < 3 ? milestones[0] : "",
    version: versions[index % versions.length],
    priority: index > 2 && index < 7 ? "Thấp" : "Trung bình",
    creator: "SYP My",
    created: index < 2 ? "2026-08-28" : "2026-09-04",
    start: "2026-08-28",
    due: "",
    updated: "2026-09-14",
    estimate: "",
    actual: "",
    reason: status === "closed" ? "Đã khắc phục" : "",
    description: `## Mô tả vấn đề\n${title.replace(/【|】/g, " ")}.\n\n## Các bước tái hiện\n1. Đăng nhập ứng dụng bằng tài khoản hợp lệ.\n2. Mở chức năng tương ứng trong dự án.\n3. Thực hiện thao tác và kiểm tra kết quả.\n\n## Kết quả thực tế\nNội dung hiển thị chưa đúng như mong đợi.\n\n## Kết quả mong đợi\nHiển thị đầy đủ, chính xác theo đặc tả đã thống nhất.\n\n## Môi trường\niPad · iOS 18 · Phiên bản 1.2.0 (160)`,
    comments: [],
  }),
);
export const initialActivities = [
  {
    id: 1,
    issueId: "SFLUTTER-6071",
    user: "SYP Huyen",
    minutes: 7,
    text: "",
    status: "ready",
  },
  {
    id: 2,
    issueId: "SFLUTTER-6071",
    user: "SYP Huyen",
    minutes: 8,
    text: "@Nguyễn Giáp\n\nMình đã thực hiện kiểm thử lại và xin chia sẻ kết quả.\n\n【Môi trường】itec-test4 / Phiên bản ứng dụng 1.2.0 (160)\nKết quả: Danh sách ảnh chỉ dẫn vẫn chưa được xuất đầy đủ trong tệp PDF. Nhờ bạn kiểm tra lại giúp mình.",
    status: "open",
  },
  {
    id: 3,
    issueId: "SFLUTTER-6091",
    user: "SYP Huyen",
    minutes: 10,
    text: "Đã kiểm thử trên Apple iPad thế hệ 11 (iOS 18) / 1.2.0 (160).\nKhông còn tái hiện lỗi. Kết quả kiểm thử đạt yêu cầu.",
    status: "closed",
  },
  {
    id: 4,
    issueId: "SFLUTTER-5863",
    user: "Đỗ Cẩm Nhung",
    minutes: 20,
    text: "@SYP Huyen\n\nMình đã cập nhật bản sửa lỗi. Nhờ bạn kiểm tra lại trên phiên bản mới nhất.",
    status: "resolved",
  },
  {
    id: 5,
    issueId: "SFLUTTER-6112",
    user: "Phan Quốc Khánh",
    minutes: 35,
    text: "Đã xác nhận đặc tả với nhóm thiết kế. Công việc đã sẵn sàng để xử lý.",
    status: "ready",
  },
];
